spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meme_title
    username: root
    password: "!junki123"

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: update
    open-in-view: false

    logging.level:
      org:
        hibernate.SQL: debug

jwt:
  secret-key: "bWVtdGl0bGVpc3ZlcnluaWNld2Vic2VydmljZWFuZGl0aXNhand0c2VjcmV0a2V5YW5kYW5kdmVyeW5pY2VpdGhpbmtpdHN3ZWJzaXRlaXNuaWNlaWFtYWdvb2Rib3lpYW1hdG9tYm95"
  access-expiration-time: 1800000
  claims:
    issuer: "memetitle"

oauth2:
  provider:
    kakao:
      client-id: "5e126202c18a4006a3db7a30a84fadb4"
      client-secret: "uECCdSnELXq5tSrb7GjoVH6fg5aLQ6h0"
      redirect-url: "http://localhost:8080/login/kakao"
      token-url: "https://kauth.kakao.com/oauth/token"
